/* ATSHREE growth features: wishlist, reviews, search/filter, product galleries, recommendations, notifications and return requests. */
(function(){
 const sbReady=window.atshreeSupabaseReady||Promise.resolve(window.atshreeSupabase);
 const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
 const money2=n=>window.money?money(n):'₹'+Number(n||0).toLocaleString('en-IN');
 async function user(){await sbReady; if(!window.atshreeSupabase)return null; return (await window.atshreeSupabase.auth.getUser()).data?.user||null;}
 async function wishlistIds(){const u=await user();if(!u)return[];const r=await window.atshreeSupabase.from('wishlists').select('product_id').eq('user_id',u.id);return r.data?.map(x=>Number(x.product_id))||[];}
 async function toggleWishlist(id,button){const u=await user();if(!u){location.href='/account.html';return;}const sb=window.atshreeSupabase;const existing=await sb.from('wishlists').select('id').eq('user_id',u.id).eq('product_id',id).maybeSingle();if(existing.data){await sb.from('wishlists').delete().eq('id',existing.data.id);button.classList.remove('active');button.textContent='♡';}else{await sb.from('wishlists').insert({user_id:u.id,product_id:id});button.classList.add('active');button.textContent='♥';}}
 window.atshreeToggleWishlist=toggleWishlist;
 function enhanceCards(){document.querySelectorAll('.product').forEach(card=>{const link=card.querySelector('a[href*="product.html?id="]');if(!link||card.querySelector('.wishBtn'))return;const id=Number(new URL(link.href,location.origin).searchParams.get('id'));const b=document.createElement('button');b.className='wishBtn';b.type='button';b.textContent='♡';b.title='Save to wishlist';b.onclick=()=>toggleWishlist(id,b);card.querySelector('.photo')?.appendChild(b);});wishlistIds().then(ids=>document.querySelectorAll('.wishBtn').forEach(b=>{const link=b.closest('.product').querySelector('a[href*="product.html?id="]');const id=Number(new URL(link.href,location.origin).searchParams.get('id'));if(ids.includes(id)){b.classList.add('active');b.textContent='♥';}}));}
 window.addEventListener('atshree-products-ready',enhanceCards);setTimeout(enhanceCards,1200);
 function shopEnhance(){const host=document.querySelector('#shop');if(!host)return;const wrap=host.parentElement;let tools=document.querySelector('#shopTools');if(!tools){tools=document.createElement('div');tools.id='shopTools';tools.className='shopTools';tools.innerHTML='<input id="shopSearch" placeholder="Search products…"><select id="shopSort"><option value="featured">Featured</option><option value="new">Newest</option><option value="low">Price: Low to High</option><option value="high">Price: High to Low</option><option value="sale">On Sale</option></select><select id="shopSize"><option value="">All sizes</option><option>S</option><option>M</option><option>L</option><option>XL</option><option>XXL</option></select>';wrap.insertBefore(tools,host);}
 const apply=()=>{const q=(document.querySelector('#shopSearch')?.value||'').toLowerCase(),sort=document.querySelector('#shopSort')?.value||'featured',size=document.querySelector('#shopSize')?.value||'',cat=new URLSearchParams(location.search).get('category')||'All';let a=(window.PRODUCTS||[]).filter(p=>(cat==='All'||p.c===cat)&&(!q||`${p.n} ${p.c} ${p.description||''} ${p.fabric||''}`.toLowerCase().includes(q))&&(!size||(p.sizes||[]).includes(size)));if(sort==='low')a.sort((x,y)=>(x.sale??x.p)-(y.sale??y.p));if(sort==='high')a.sort((x,y)=>(y.sale??y.p)-(x.sale??x.p));if(sort==='sale')a=a.filter(p=>p.sale!=null);if(sort==='new')a.sort((x,y)=>Number(y.id)-Number(x.id));window.render(a,'#shop');document.querySelector('#count').textContent=a.length+' products';enhanceCards();};['shopSearch','shopSort','shopSize'].forEach(id=>document.addEventListener('input',e=>{if(e.target.id===id)apply();}));window.atshreeApplyShopFilters=apply;apply();}
 setTimeout(shopEnhance,500);window.addEventListener('atshree-products-ready',shopEnhance);
 async function productEnhance(){const detail=document.querySelector('#detail');if(!detail)return;const id=Number(new URLSearchParams(location.search).get('id'))||1;await sbReady;const sb=window.atshreeSupabase;let gallery=[];if(sb){const r=await sb.from('product_images').select('*').eq('product_id',id).order('sort_order');gallery=r.data||[];}const p=(window.PRODUCTS||[]).find(x=>Number(x.id)===id);if(!p)return;const main=p.i;const images=[{image_url:main,alt_text:p.n},...gallery.filter(x=>x.image_url!==main)];const media=detail.querySelector('.detail>div:first-child');if(media){media.innerHTML=`<div class="productGalleryMain"><img id="mainProductImage" src="${esc(images[0].image_url)}" alt="${esc(p.n)}"></div><div class="productThumbs">${images.map((x,i)=>`<button type="button" data-img="${esc(x.image_url)}"><img src="${esc(x.image_url)}" alt="${esc(x.alt_text||p.n)}"></button>`).join('')}</div>`;media.querySelectorAll('[data-img]').forEach(b=>b.onclick=()=>document.querySelector('#mainProductImage').src=b.dataset.img);}
 const info=detail.querySelector('.detail>div:nth-child(2)');if(!info)return;let extra=document.querySelector('#productExtras');if(!extra){extra=document.createElement('div');extra.id='productExtras';info.appendChild(extra);}const sum=sb?await sb.rpc('product_review_summary',{p_product_id:id}):{data:[{avg_rating:0,review_count:0}]};const s=sum.data?.[0]||{};extra.innerHTML=`<div class="ratingSummary"><strong>★ ${Number(s.avg_rating||0).toFixed(1)}</strong> <span>${Number(s.review_count||0)} reviews</span></div><button class="wishLarge" id="detailWish">♡ SAVE TO WISHLIST</button><div class="sizeGuide"><strong>SIZE GUIDE</strong><p>Choose your usual Indian size. For a relaxed fit, consider one size up.</p><a href="/size-guide.html">View detailed size guide →</a></div><div class="completeLook"><div class="ey">COMPLETE THE LOOK</div><h3>Pair it with another ATSHREE favourite.</h3><div id="relatedProducts" class="miniRelated"></div></div><div class="reviews"><div class="ey">CUSTOMER REVIEWS</div><div id="reviewList">Loading reviews…</div><form id="reviewForm" class="reviewForm"><select id="reviewRating"><option value="5">★★★★★</option><option value="4">★★★★☆</option><option value="3">★★★☆☆</option><option value="2">★★☆☆☆</option><option value="1">★☆☆☆☆</option></select><textarea id="reviewText" placeholder="Share your experience…" required></textarea><button class="btn" type="submit">SUBMIT REVIEW</button></form></div>`;
 const wb=document.querySelector('#detailWish');if(wb){const ids=await wishlistIds();wb.classList.toggle('active',ids.includes(id));wb.textContent=ids.includes(id)?'♥ SAVED TO WISHLIST':'♡ SAVE TO WISHLIST';wb.onclick=()=>toggleWishlist(id,wb);}
 const rel=(window.PRODUCTS||[]).filter(x=>x.id!==id&&x.c===p.c).slice(0,3);document.querySelector('#relatedProducts').innerHTML=rel.map(x=>`<a href="/product.html?id=${x.id}"><img src="${esc(x.i)}"><span>${esc(x.n)}</span><strong>${money2(x.sale??x.p)}</strong></a>`).join('');
 async function loadReviews(){if(!sb)return;const r=await sb.from('product_reviews').select('rating,review,created_at,profiles(full_name)').eq('product_id',id).eq('approved',true).order('created_at',{ascending:false});document.querySelector('#reviewList').innerHTML=r.data?.length?r.data.map(x=>`<article class="review"><div>★ ${x.rating}/5</div><p>${esc(x.review)}</p><small>${esc(x.profiles?.full_name||'Verified customer')} · Verified Purchase</small></article>`).join(''):'<p class="secureText">No reviews yet. Be the first to review this piece.</p>';}
 document.querySelector('#reviewForm').onsubmit=async e=>{e.preventDefault();const u=await user();if(!u){location.href='/account.html';return;}const r=await sb.from('product_reviews').upsert({product_id:id,user_id:u.id,rating:Number(document.querySelector('#reviewRating').value),review:document.querySelector('#reviewText').value.trim(),approved:false},{onConflict:'product_id,user_id'});if(r.error)alert(r.error.message);else{document.querySelector('#reviewText').value='';alert('Review submitted for approval.');}};loadReviews();}
 setTimeout(productEnhance,700);window.addEventListener('atshree-products-ready',productEnhance);
 async function accountExtras(){const area=document.querySelector('#accountArea');if(!area)return;await sbReady;const u=await user();if(!u)return;const sb=window.atshreeSupabase;const r=await sb.from('wishlists').select('product_id,products(id,name,image_url,price,sale_price)').eq('user_id',u.id).order('created_at',{ascending:false});const box=document.createElement('div');box.className='accountCard';box.innerHTML='<div class="ey">WISHLIST</div><h2>Your saved pieces</h2><div class="wishlistGrid">'+(r.data?.length?r.data.map(x=>`<a href="/product.html?id=${x.product_id}"><img src="${esc(x.products?.image_url||'/assets/products/ivory-kurta.jpg')}"><strong>${esc(x.products?.name||'Product')}</strong><span>${money2(x.products?.sale_price??x.products?.price)}</span></a>`).join(''):'<p class="secureText">Your wishlist is empty.</p>')+'</div>';area.appendChild(box);const n=await sb.from('notifications').select('*').eq('user_id',u.id).is('read_at',null).order('created_at',{ascending:false}).limit(8);if(n.data?.length){const nb=document.createElement('div');nb.className='accountCard';nb.innerHTML='<div class="ey">NOTIFICATIONS</div>'+n.data.map(x=>`<div class="notification"><strong>${esc(x.title)}</strong><p>${esc(x.body)}</p>${x.link?`<a href="${esc(x.link)}">VIEW →</a>`:''}</div>`).join('');area.appendChild(nb);}}
 setTimeout(accountExtras,1600);
 async function adminExtras(){if(!document.querySelector('#adminMessage'))return;await new Promise(r=>setTimeout(r,1200));const host=document.querySelector('#productsList');if(!host)return;const sb=window.atshreeSupabase||window.supabase; if(!sb)return;host.querySelectorAll('.productRow').forEach(row=>{if(row.querySelector('.galleryBtn'))return;const edit=row.querySelector('[data-edit]');if(!edit)return;const id=Number(edit.dataset.edit);const b=document.createElement('button');b.className='galleryBtn';b.textContent='GALLERY';b.onclick=async()=>{const url=prompt('Paste additional image URL for this product');if(!url)return;const r=await sb.from('product_images').insert({product_id:id,image_url:url.trim(),sort_order:10});if(r.error)alert(r.error.message);else alert('Gallery image added.');};row.querySelector('.productRowActions')?.appendChild(b);});}
 setInterval(adminExtras,1800);
})();