const SUPABASE_URL="https://schsitbayzsqalkvnpbs.supabase.co";const SUPABASE_PUBLISHABLE_KEY="sb_publishable_rHtZGmayQqlWsI-gJt-i8g_6_7LnaFz";const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);window.supabaseClient=supabaseClient;const AUTH_EMAIL_COOLDOWN_MS=65000,AUTH_SIGNUP_LOCK='atshree_auth_signup_lock',AUTH_RECOVERY_LOCK='atshree_auth_recovery_lock';function authCooldownRemaining(key){const last=Number(localStorage.getItem(key)||0);return Math.max(0,AUTH_EMAIL_COOLDOWN_MS-(Date.now()-last))}function markAuthEmailAttempt(key){localStorage.setItem(key,String(Date.now()))}const originalSignUp=supabaseClient.auth.signUp.bind(supabaseClient.auth);supabaseClient.auth.signUp=async(...args)=>{const remaining=authCooldownRemaining(AUTH_SIGNUP_LOCK);if(remaining>0)return{data:{user:null,session:null},error:new Error(`Please wait ${Math.ceil(remaining/1000)} seconds before trying again.`)}markAuthEmailAttempt(AUTH_SIGNUP_LOCK);return originalSignUp(...args)};const originalRecovery=supabaseClient.auth.resetPasswordForEmail.bind(supabaseClient.auth);supabaseClient.auth.resetPasswordForEmail=async(...args)=>{const remaining=authCooldownRemaining(AUTH_RECOVERY_LOCK);if(remaining>0)return{data:{},error:new Error(`Please wait ${Math.ceil(remaining/1000)} seconds before requesting another reset email.`)}markAuthEmailAttempt(AUTH_RECOVERY_LOCK);return originalRecovery(...args)};

async function addAdminAccessButton(){try{const{data:{user}}=await supabaseClient.auth.getUser();if(!user)return;const{data:profile}=await supabaseClient.from('profiles').select('is_admin').eq('id',user.id).maybeSingle();if(!profile?.is_admin)return;const navRight=document.querySelector('.navRight');if(navRight&&!document.querySelector('[data-atshree-admin-nav]')){const link=document.createElement('a');link.href='/admin-login.html';link.className='accountLink';link.dataset.atshreeAdminNav='true';link.textContent='ADMIN';navRight.insertBefore(link,navRight.firstChild)}const area=document.querySelector('#accountArea');if(area&&!area.querySelector('[data-atshree-admin-card]')){const card=document.createElement('div');card.className='accountCard';card.dataset.atshreeAdminCard='true';card.style.marginTop='18px';card.innerHTML='<div class="ey">ATSHREE CONTROL CENTER</div><h2>Admin Dashboard</h2><p>Manage products, inventory, orders, customers, coupons, POS, SKU & barcode tools and reports.</p><a class="btn" href="/admin-login.html">OPEN ADMIN LOGIN</a>';area.appendChild(card)}}catch(e){console.warn('Admin indicator unavailable',e)}}
function startAdminIndicator(){addAdminAccessButton();setTimeout(addAdminAccessButton,500);setTimeout(addAdminAccessButton,1500);const area=document.querySelector('#accountArea');if(area&&!area.dataset.adminObserver){area.dataset.adminObserver='true';new MutationObserver(()=>addAdminAccessButton()).observe(area,{childList:true,subtree:true})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',startAdminIndicator);else startAdminIndicator();supabaseClient.auth.onAuthStateChange(()=>setTimeout(addAdminAccessButton,250));
function loadAtshreeScript(src,key){if(document.querySelector(`script[data-atshree-script="${key}"]`))return;const s=document.createElement('script');s.src=src;s.dataset.atshreeScript=key;document.head.appendChild(s)}
loadAtshreeScript('/customer-verification.js','customer-verification');

// Admin protection: use the single dedicated admin-login.html flow.
// admin.html itself stays hidden until a valid admin session exists; non-admin users are sent to the canonical login page.
(async function adminPortalGuard(){if(location.pathname!=='/admin.html')return;const main=document.querySelector('main');if(!main)return;main.style.visibility='hidden';try{const{data:{user},error}=await supabaseClient.auth.getUser();if(error)throw error;if(!user){location.replace('/admin-login.html');return}const{data:profile,error:pe}=await supabaseClient.from('profiles').select('is_admin').eq('id',user.id).maybeSingle();if(pe)throw pe;if(!profile?.is_admin){await supabaseClient.auth.signOut();location.replace('/admin-login.html');return}main.style.visibility='visible';}catch(error){console.error('Admin authorization check failed:',error);location.replace('/admin-login.html')}})();