const SUPABASE_URL="https://schsitbayzsqalkvnpbs.supabase.co";const SUPABASE_PUBLISHABLE_KEY="sb_publishable_rHtZGmayQqlWsI-g8g_6_7LnaFz";const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);window.supabaseClient=supabaseClient;const AUTH_EMAIL_COOLDOWN_MS=65000,AUTH_SIGNUP_LOCK='atshree_auth_signup_lock',AUTH_RECOVERY_LOCK='atshree_auth_recovery_lock';function authCooldownRemaining(key){const last=Number(localStorage.getItem(key)||0);return Math.max(0,AUTH_EMAIL_COOLDOWN_MS-(Date.now()-last))}function markAuthEmailAttempt(key){localStorage.setItem(key,String(Date.now()))}const originalSignUp=supabaseClient.auth.signUp.bind(supabaseClient.auth);supabaseClient.auth.signUp=async(...args)=>{const remaining=authCooldownRemaining(AUTH_SIGNUP_LOCK);if(remaining>0)return{data:{user:null,session:null},error:new Error(`Please wait ${Math.ceil(remaining/1000)} seconds before trying again.`)}markAuthEmailAttempt(AUTH_SIGNUP_LOCK);return originalSignUp(...args)};const originalRecovery=supabaseClient.auth.resetPasswordForEmail.bind(supabaseClient.auth);supabaseClient.auth.resetPasswordForEmail=async(...args)=>{const remaining=authCooldownRemaining(AUTH_RECOVERY_LOCK);if(remaining>0)return{data:{},error:new Error(`Please wait ${Math.ceil(remaining/1000)} seconds before requesting another reset email.`)}markAuthEmailAttempt(AUTH_RECOVERY_LOCK);return originalRecovery(...args)};

async function addAdminAccessButton(){try{const{data:{user}}=await supabaseClient.auth.getUser();if(!user)return;const{data:profile}=await supabaseClient.from('profiles').select('is_admin').eq('id',user.id).maybeSingle();if(!profile?.is_admin)return;const navRight=document.querySelector('.navRight');if(navRight&&!document.querySelector('[data-atshree-admin-nav]')){const link=document.createElement('a');link.href='/admin.html';link.className='accountLink';link.dataset.atshreeAdminNav='true';link.textContent='ADMIN';navRight.insertBefore(link,navRight.firstChild)}const area=document.querySelector('#accountArea');if(area&&!area.querySelector('[data-atshree-admin-card]')){const card=document.createElement('div');card.className='accountCard';card.dataset.atshreeAdminCard='true';card.style.marginTop='18px';card.innerHTML='<div class="ey">ATSHREE CONTROL CENTER</div><h2>Admin Dashboard</h2><p>Manage products, inventory, orders, customers, coupons, POS, SKU & barcode tools and reports.</p><a class="btn" href="/admin.html">OPEN ADMIN DASHBOARD</a>';area.appendChild(card)}}catch(e){console.warn('Admin indicator unavailable',e)}}

/* Run the admin indicator after the account page renders and whenever its DOM is rebuilt. */
function startAdminIndicator(){addAdminAccessButton();setTimeout(addAdminAccessButton,500);setTimeout(addAdminAccessButton,1500);const area=document.querySelector('#accountArea');if(area&&!area.dataset.adminObserver){area.dataset.adminObserver='true';new MutationObserver(()=>addAdminAccessButton()).observe(area,{childList:true,subtree:true})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',startAdminIndicator);else startAdminIndicator();supabaseClient.auth.onAuthStateChange(()=>setTimeout(addAdminAccessButton,250));

/* Dedicated ATSHREE admin portal: verify the existing account and allow a direct admin sign-in. */
(async function adminPortalGuard(){
  if(location.pathname!=='/admin.html')return;
  const main=document.querySelector('main');if(!main)return;
  const style=document.createElement('style');style.textContent='.atshreeAdminGate{position:fixed;inset:0;z-index:999999;background:#f7f5f1;display:flex;align-items:center;justify-content:center;padding:24px}.atshreeAdminGateCard{width:min(430px,100%);box-sizing:border-box;background:#fff;border:1px solid #ddd;padding:32px;box-shadow:0 18px 60px rgba(0,0,0,.08)}.atshreeAdminGateCard h1{font:400 34px Georgia,serif;margin:8px 0}.atshreeAdminGateForm{display:grid;gap:12px;margin-top:22px}.atshreeAdminGateForm input{width:100%;box-sizing:border-box;padding:13px;border:1px solid #ccc;background:#fff}.atshreeAdminGateForm button{padding:13px;border:1px solid #17130f;background:#17130f;color:#fff;cursor:pointer}.atshreeAdminGateMsg{min-height:20px;margin-top:12px;font-size:13px;color:#8b2f2f}.atshreeAdminGateMsg.ok{color:#246b36}';document.head.appendChild(style);
  const gate=document.createElement('div');gate.className='atshreeAdminGate';gate.innerHTML='<div class="atshreeAdminGateCard"><div class="ey">ATSHREE CONTROL CENTER</div><h1>Admin Login</h1><p>Sign in with your existing ATSHREE administrator account.</p><form class="atshreeAdminGateForm" id="atshreeAdminGateForm"><input id="atshreeAdminEmail" type="email" autocomplete="username" placeholder="Admin email" required><input id="atshreeAdminPassword" type="password" autocomplete="current-password" placeholder="Password" required><button id="atshreeAdminSignIn" type="submit">LOGIN TO ADMIN</button></form><div id="atshreeAdminGateMsg" class="atshreeAdminGateMsg"></div><a href="/account.html" style="font-size:12px;text-decoration:underline">BACK TO ACCOUNT</a></div>';document.body.appendChild(gate);main.style.visibility='hidden';
  const msg=document.querySelector('#atshreeAdminGateMsg'),btn=document.querySelector('#atshreeAdminSignIn');
  async function verify(){const{data:{user},error}=await supabaseClient.auth.getUser();if(error)return{ok:false,message:error.message};if(!user)return{ok:false,message:''};const{data:profile,error:pe}=await supabaseClient.from('profiles').select('is_admin').eq('id',user.id).maybeSingle();if(pe)return{ok:false,message:pe.message};if(!profile?.is_admin){await supabaseClient.auth.signOut();return{ok:false,message:'This account is not authorized for admin access.'}}return{ok:true,user}}
  const current=await verify();if(current.ok){gate.remove();main.style.visibility='visible';return}
  document.querySelector('#atshreeAdminGateForm').addEventListener('submit',async e=>{e.preventDefault();btn.disabled=true;btn.textContent='SIGNING IN…';msg.textContent='';try{const email=document.querySelector('#atshreeAdminEmail').value.trim(),password=document.querySelector('#atshreeAdminPassword').value;const{error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)throw error;const result=await verify();if(!result.ok)throw new Error(result.message||'Unable to verify admin access.');gate.remove();main.style.visibility='visible'}catch(err){msg.textContent=err?.message||'Unable to sign in.'}finally{btn.disabled=false;btn.textContent='LOGIN TO ADMIN'}})
})();